/**
 * countryMasks.ts
 * Country grid masks generated by rasterizing simplified border polygons
 * onto a 25×20 grid using ray casting.
 *
 * Grid convention:
 *   col 0 = west edge (minLng), col 24 = east edge (maxLng)
 *   row 0 = NORTH edge (maxLat), row 19 = south edge (minLat)
 */

export interface CountryBBox {
  minLat: number;
  maxLat: number;
  minLng: number;
  maxLng: number;
}

export interface CountryGrid {
  id: string;
  name: string;
  bbox: CountryBBox;
  cols: number;
  rows: number;
  mask: Set<string>; // "col,row"
}

// ─── Mask builder from row spans ──────────────────────────────────────────────
// Each entry: [row, start1, end1, start2, end2, ...]
type RowSpans = number[][];

function buildMask(spans: RowSpans): Set<string> {
  const s = new Set<string>();
  for (const entry of spans) {
    const row = entry[0];
    for (let i = 1; i < entry.length; i += 2) {
      const start = entry[i];
      const end   = entry[i + 1];
      for (let col = start; col <= end; col++) {
        s.add(`${col},${row}`);
      }
    }
  }
  return s;
}

// ─── Spain 25×20 — bbox: lat 35.9–43.8, lng -9.3–4.3 ────────────────────────
const ES_SPANS: RowSpans = [
  [0, 3, 5],
  [1, 2, 13],
  [2, 1, 15],
  [3, 1, 13, 16, 20],
  [4, 1, 12, 17, 21],
  [5, 2, 5, 10, 10, 17, 22],
  [6, 4, 4, 18, 22],
  [7, 4, 5, 18, 20],
  [8, 5, 6, 18, 19],
  [9, 4, 8, 16, 17],
  [10, 4, 10, 15, 17],
  [11, 4, 12, 14, 16],
  [12, 4, 12, 15, 16],
  [13, 4, 12, 16, 16],
  [14, 3, 13, 16, 17],
  [15, 3, 14, 16, 18],
  [16, 3, 13],
  [17, 5, 13],
  [18, 6, 10],
  [19, 6, 7],
];

// ─── Portugal 25×20 — bbox: lat 36.9–42.1, lng -9.5– -6.2 ───────────────────
const PT_SPANS: RowSpans = [
  [0, 3, 18],
  [1, 0, 18],
  [2, 0, 19],
  [3, 1, 19],
  [4, 1, 18],
  [5, 1, 19],
  [6, 1, 19],
  [7, 1, 19],
  [8, 1, 18],
  [9, 0, 18],
  [10, 0, 18],
  [11, 0, 17],
  [12, 0, 17],
  [13, 0, 16],
  [14, 0, 15],
  [15, 0, 15],
  [16, 1, 14],
  [17, 2, 14],
  [18, 3, 15],
  [19, 4, 20],
];

// ─── France 25×20 — bbox: lat 41.3–51.1, lng -5.1–9.6 ───────────────────────
const FR_SPANS: RowSpans = [
  [0, 11, 12],
  [1, 10, 14],
  [2, 10, 16],
  [3, 6, 18],
  [4, 5, 19],
  [5, 1, 20],
  [6, 3, 21],
  [7, 5, 20],
  [8, 5, 20],
  [9, 5, 19],
  [10, 5, 19],
  [11, 6, 19],
  [12, 6, 19],
  [13, 6, 20],
  [14, 6, 20],
  [15, 6, 20],
  [16, 7, 9],
];

// ─── Germany 25×20 — bbox: lat 47.3–55.1, lng 6.0–15.0 ──────────────────────
const DE_SPANS: RowSpans = [
  [0, 10, 13],
  [1, 8, 18],
  [2, 7, 21],
  [3, 5, 23],
  [4, 3, 23],
  [5, 1, 23],
  [6, 0, 23],
  [7, 0, 23],
  [8, 0, 23],
  [9, 0, 23],
  [10, 0, 24],
  [11, 0, 21],
  [12, 0, 12],
  [13, 0, 11],
  [14, 1, 11],
  [15, 1, 10],
  [16, 1, 10],
  [17, 2, 10],
  [18, 2, 9],
];

// ─── Italy 25×20 — bbox: lat 36.6–47.1, lng 6.7–18.5 ────────────────────────
const IT_SPANS: RowSpans = [
  [5, 7, 13],
  [6, 8, 14],
  [7, 10, 15],
  [8, 11, 15],
  [9, 11, 16],
  [10, 12, 16],
  [11, 13, 17],
  [12, 14, 17],
  [13, 15, 18],
  [14, 16, 18],
  [15, 17, 19],
  [16, 18, 19],
];

// ─── United Kingdom 25×20 — bbox: lat 49.9–60.9, lng -8.2–1.8 ───────────────
const GB_SPANS: RowSpans = [
  [4, 9, 15],
  [5, 5, 15],
  [6, 5, 10],
  [7, 6, 8],
  [8, 7, 7],
  [9, 7, 12],
  [10, 7, 14],
  [11, 8, 19],
  [12, 10, 19],
  [13, 12, 21],
  [14, 13, 24],
  [15, 13, 23],
  [16, 13, 23],
  [17, 12, 24],
  [18, 10, 17],
  [19, 7, 14],
];

// ─── USA continental 25×20 — bbox: lat 24.4–49.4, lng -125.0– -66.9 ─────────
const US_SPANS: RowSpans = [
  [0, 2, 13],
  [1, 0, 15],
  [2, 0, 17, 24, 24],
  [3, 0, 18, 23, 24],
  [4, 0, 24],
  [5, 0, 23],
  [6, 0, 22],
  [7, 0, 21],
  [8, 1, 21],
  [9, 1, 21],
  [10, 1, 20],
  [11, 2, 20],
  [12, 2, 19],
  [13, 3, 3, 5, 19],
  [14, 8, 18],
  [15, 9, 15],
  [16, 10, 12],
  [17, 12, 12],
];

// ─── Brazil 25×20 — bbox: lat -33.7–5.3, lng -73.9– -34.8 ───────────────────
const BR_SPANS: RowSpans = [
  [0, 1, 13],
  [1, 2, 14],
  [2, 3, 15],
  [3, 3, 18],
  [4, 3, 21],
  [5, 2, 24],
  [6, 1, 24],
  [7, 1, 24],
  [8, 3, 23],
  [9, 4, 22],
  [10, 6, 22],
  [11, 9, 21],
  [12, 10, 21],
  [13, 10, 20],
  [14, 11, 19],
  [15, 11, 18],
  [16, 12, 17],
  [17, 12, 16],
  [18, 12, 14],
  [19, 13, 13],
];

// ─── Australia 25×20 — bbox: lat -43.6– -10.7, lng 113.2–153.6 ──────────────
const AU_SPANS: RowSpans = [
  [0, 17, 17],
  [1, 11, 14, 17, 17],
  [2, 7, 15, 17, 18],
  [3, 6, 15, 17, 19],
  [4, 5, 19],
  [5, 3, 20],
  [6, 1, 21],
  [7, 0, 22],
  [8, 0, 23],
  [9, 0, 23],
  [10, 0, 24],
  [11, 0, 24],
  [12, 0, 24],
  [13, 1, 9, 12, 23],
  [14, 14, 22],
  [15, 17, 22],
  [16, 18, 21],
];

// ─── Registry ─────────────────────────────────────────────────────────────────
export const COUNTRY_GRIDS: Record<string, CountryGrid> = {
  es: {
    id: "es", name: "Spain",
    bbox: { minLat: 35.9, maxLat: 43.8, minLng: -9.3, maxLng: 4.3 },
    cols: 25, rows: 20,
    mask: buildMask(ES_SPANS),
  },
  pt: {
    id: "pt", name: "Portugal",
    bbox: { minLat: 36.9, maxLat: 42.1, minLng: -9.5, maxLng: -6.2 },
    cols: 25, rows: 20,
    mask: buildMask(PT_SPANS),
  },
  fr: {
    id: "fr", name: "France",
    bbox: { minLat: 41.3, maxLat: 51.1, minLng: -5.1, maxLng: 9.6 },
    cols: 25, rows: 20,
    mask: buildMask(FR_SPANS),
  },
  de: {
    id: "de", name: "Germany",
    bbox: { minLat: 47.3, maxLat: 55.1, minLng: 6.0, maxLng: 15.0 },
    cols: 25, rows: 20,
    mask: buildMask(DE_SPANS),
  },
  it: {
    id: "it", name: "Italy",
    bbox: { minLat: 36.6, maxLat: 47.1, minLng: 6.7, maxLng: 18.5 },
    cols: 25, rows: 20,
    mask: buildMask(IT_SPANS),
  },
  gb: {
    id: "gb", name: "United Kingdom",
    bbox: { minLat: 49.9, maxLat: 60.9, minLng: -8.2, maxLng: 1.8 },
    cols: 25, rows: 20,
    mask: buildMask(GB_SPANS),
  },
  us: {
    id: "us", name: "United States",
    bbox: { minLat: 24.4, maxLat: 49.4, minLng: -125.0, maxLng: -66.9 },
    cols: 25, rows: 20,
    mask: buildMask(US_SPANS),
  },
  br: {
    id: "br", name: "Brazil",
    bbox: { minLat: -33.7, maxLat: 5.3, minLng: -73.9, maxLng: -34.8 },
    cols: 25, rows: 20,
    mask: buildMask(BR_SPANS),
  },
  au: {
    id: "au", name: "Australia",
    bbox: { minLat: -43.6, maxLat: -10.7, minLng: 113.2, maxLng: 153.6 },
    cols: 25, rows: 20,
    mask: buildMask(AU_SPANS),
  },
};

/**
 * Convert lat/lng to grid (col, row).
 * Returns null if outside bbox or outside country mask.
 */
export function latLngToCell(
  lat: number,
  lng: number,
  grid: CountryGrid
): { col: number; row: number } | null {
  const { bbox, cols, rows, mask } = grid;

  if (lat < bbox.minLat || lat > bbox.maxLat || lng < bbox.minLng || lng > bbox.maxLng) {
    return null;
  }

  const col = Math.min(cols - 1, Math.floor(((lng - bbox.minLng) / (bbox.maxLng - bbox.minLng)) * cols));
  const row = Math.min(rows - 1, Math.floor(((bbox.maxLat - lat)  / (bbox.maxLat - bbox.minLat)) * rows));

  // Return cell even if not in mask — caller decides whether to render
  return { col, row };
}

/**
 * Check if a cell is inside the country mask.
 */
export function isInMask(col: number, row: number, grid: CountryGrid): boolean {
  return grid.mask.has(`${col},${row}`);
}
